Repository oconnormi/docker-ddf-base, pull requests merged in 2019-01, with the labels that each got.

#52 Added missing wfr exclusion
  2.14/linux/entrypoint/global_env.sh
Labels: in progress

#53 Fix hostname and port settings, update variable names
  2.14/linux/entrypoint/certs_env.sh
  2.14/linux/entrypoint/global_env.sh
  2.14/linux/entrypoint/load_certs.sh
  2.14/linux/entrypoint/local_ca_request.sh
  2.14/linux/entrypoint/pre_start.sh
  2.14/linux/entrypoint/remote_ca_request.sh
  README.md
Labels: enhancement, in progress, maturity

#54 Automate adding sources
  2.14/linux/alpine/Dockerfile
  2.14/linux/alpine/Dockerfile.test
  2.14/linux/argbash-templates/create-source.m4
  2.14/linux/argbash-templates/tests/create-source.bats
  2.14/linux/centos/Dockerfile
  2.14/linux/entrypoint/files/templates/sources/csw_federated.config
  2.14/linux/entrypoint/global_env.sh
  2.14/linux/entrypoint/pre_start.sh
  2.14/linux/entrypoint/sources.sh
  2.14/linux/tests/sources.bats
Labels: enhancement, in progress
